name: Execute Python File on SUMMARY.md Change

on:
  push:
    branches:
      - main

jobs:
  execute_python:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Check SUMMARY.md Changes
        env:
          DIFF: ${{ steps.git-diff-action.outputs.json-diff-path }}
        run: 
          echo $DIFF
          python test.py $DIFF
