name: Execute Python File on SUMMARY.md Change

on:
  push:
    branches:
      - main

jobs:
  execute_python:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt # 필요한 종속성이 있다면 requirements.txt에 추가해주세요.
      
      - name: Check for SUMMARY.md changes
        id: check_changes
        run: |
          changes=$(git diff --name-only HEAD~1..HEAD SUMMARY.md)
          echo "::set-output name=changes::$changes"
        
      - name: Run Python file if SUMMARY.md has changed
        run: |
          changes=$INPUT_CHANGES
          if [[ -n "$changes" ]]; then
            python test.py "$changes" # 파이썬 파일명과 변경 내용을 처리하는 로직을 자신의 파일에 맞게 수정해주세요.
          fi
